# Generated by Django 5.0.3 on 2024-04-09 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("ean_isbn13", models.CharField(blank=True, max_length=13)),
                ("upc_isbn10", models.CharField(blank=True, max_length=10)),
                ("author_first_name", models.CharField(blank=True, max_length=100)),
                ("author_last_name", models.CharField(blank=True, max_length=100)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("genre", models.CharField(blank=True, max_length=40)),
                ("status", models.CharField(blank=True, max_length=40)),
                ("rating", models.CharField(blank=True, max_length=50)),
                ("item_type", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="Librarians",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("document", models.CharField(max_length=20)),
                ("birth_date", models.DateField()),
                ("full_address", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Librarian",
                "verbose_name_plural": "Librarians",
            },
        ),
        migrations.CreateModel(
            name="LoanLibrarians",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "librarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_librarians",
                        to="biblioteca.librarians",
                    ),
                ),
            ],
            options={
                "verbose_name": "LoanLibrarian",
                "verbose_name_plural": "LoanLibrarians",
            },
        ),
        migrations.CreateModel(
            name="LoanResponsibles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "LoanResponsible",
                "verbose_name_plural": "LoanResponsibles",
            },
        ),
        migrations.CreateModel(
            name="Loans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100)),
                ("loan_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("expected_return_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="biblioteca.books",
                    ),
                ),
                (
                    "responsible_librarian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_responsible_librarian",
                        to="biblioteca.librarians",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan",
                "verbose_name_plural": "Loans",
            },
        ),
        migrations.CreateModel(
            name="Persons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("document", models.CharField(max_length=11)),
                ("birth_date", models.DateField()),
                ("full_address", models.CharField(max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(blank=True, max_length=100)),
                ("responsible_document", models.CharField(blank=True, max_length=11)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.CreateModel(
            name="Responsibles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=20)),
                ("birth_date", models.DateField()),
                ("full_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=20)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Responsible",
                "verbose_name_plural": "Responsibles",
            },
        ),
        migrations.DeleteModel(
            name="Test",
        ),
        migrations.AddField(
            model_name="loanresponsibles",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_responsibles",
                to="biblioteca.loans",
            ),
        ),
        migrations.AddField(
            model_name="loanlibrarians",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_librarians",
                to="biblioteca.loans",
            ),
        ),
        migrations.AddField(
            model_name="loans",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_loans",
                to="biblioteca.persons",
            ),
        ),
        migrations.AddField(
            model_name="loanresponsibles",
            name="responsible",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_responsibles",
                to="biblioteca.responsibles",
            ),
        ),
    ]
