# Generated by Django 5.0.3 on 2024-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "biblioteca",
            "0002_books_genres_loans_status_delete_test_books_genre_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="description",
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name="books",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
