# Generated by Django 5.0.3 on 2024-05-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_address",
            field=models.CharField(max_length=260),
        ),
    ]
